# Site settings
title: 欢迎来到 Day 的blog
SEOTitle: Day的博客 | Day Blog
header-img: img/post-bg-desk.jpg
email: 15602297600@163.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, Day的博客, Day, 戴宗良, web前端, Apple, iPhone, 混合开发"
url: "http://day-19.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Day-19/Day-19.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Keep on trying!"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     hu-hu-38-45/activities
github_username:    Day-19
#facebook_username:  baiying.qiu.7
jianshu_username:   2884adbac0f5
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: Day-19

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 7c0b91a9c13a7b9bd591                            #生成的clientID
  clientSecret: dc1bfa5008da69b349a0e77b5d1abc04db173d14    #生成的clientSecret
  repo: day-19.github.io    #仓库名称
  owner: Day-19    #github用户名
  admin: Day-19
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 0c1db18d69906928607819a93e131ef0

# Google Analytics
ga_track_id: 'UA-137145901-1'          # Format: UA-xxxxxx-xx
ga_domain: dzldxy.com               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "开源中国",
        href: "https://www.oschina.net/blog?classification=428612"
    },{
        title: "简书·Day",
        href: "https://www.jianshu.com/u/2884adbac0f5"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
